/*
Copyright 2022 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	rtresourcev1 "knative.dev/serving/pkg/apis/rtresource/v1"
)

// RTResourceLister helps list RTResources.
// All objects returned here must be treated as read-only.
type RTResourceLister interface {
	// List lists all RTResources in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*rtresourcev1.RTResource, err error)
	// RTResources returns an object that can list and get RTResources.
	RTResources(namespace string) RTResourceNamespaceLister
	RTResourceListerExpansion
}

// rTResourceLister implements the RTResourceLister interface.
type rTResourceLister struct {
	listers.ResourceIndexer[*rtresourcev1.RTResource]
}

// NewRTResourceLister returns a new RTResourceLister.
func NewRTResourceLister(indexer cache.Indexer) RTResourceLister {
	return &rTResourceLister{listers.New[*rtresourcev1.RTResource](indexer, rtresourcev1.Resource("rtresource"))}
}

// RTResources returns an object that can list and get RTResources.
func (s *rTResourceLister) RTResources(namespace string) RTResourceNamespaceLister {
	return rTResourceNamespaceLister{listers.NewNamespaced[*rtresourcev1.RTResource](s.ResourceIndexer, namespace)}
}

// RTResourceNamespaceLister helps list and get RTResources.
// All objects returned here must be treated as read-only.
type RTResourceNamespaceLister interface {
	// List lists all RTResources in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*rtresourcev1.RTResource, err error)
	// Get retrieves the RTResource from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*rtresourcev1.RTResource, error)
	RTResourceNamespaceListerExpansion
}

// rTResourceNamespaceLister implements the RTResourceNamespaceLister
// interface.
type rTResourceNamespaceLister struct {
	listers.ResourceIndexer[*rtresourcev1.RTResource]
}
