/*
Copyright 2022 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	rtresourcev1 "knative.dev/serving/pkg/apis/rtresource/v1"
	scheme "knative.dev/serving/pkg/client/clientset/versioned/scheme"
)

// RTResourcesGetter has a method to return a RTResourceInterface.
// A group's client should implement this interface.
type RTResourcesGetter interface {
	RTResources(namespace string) RTResourceInterface
}

// RTResourceInterface has methods to work with RTResource resources.
type RTResourceInterface interface {
	Create(ctx context.Context, rTResource *rtresourcev1.RTResource, opts metav1.CreateOptions) (*rtresourcev1.RTResource, error)
	Update(ctx context.Context, rTResource *rtresourcev1.RTResource, opts metav1.UpdateOptions) (*rtresourcev1.RTResource, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, rTResource *rtresourcev1.RTResource, opts metav1.UpdateOptions) (*rtresourcev1.RTResource, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*rtresourcev1.RTResource, error)
	List(ctx context.Context, opts metav1.ListOptions) (*rtresourcev1.RTResourceList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *rtresourcev1.RTResource, err error)
	RTResourceExpansion
}

// rTResources implements RTResourceInterface
type rTResources struct {
	*gentype.ClientWithList[*rtresourcev1.RTResource, *rtresourcev1.RTResourceList]
}

// newRTResources returns a RTResources
func newRTResources(c *RtresourceV1Client, namespace string) *rTResources {
	return &rTResources{
		gentype.NewClientWithList[*rtresourcev1.RTResource, *rtresourcev1.RTResourceList](
			"rtresources",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *rtresourcev1.RTResource { return &rtresourcev1.RTResource{} },
			func() *rtresourcev1.RTResourceList { return &rtresourcev1.RTResourceList{} },
		),
	}
}
